/* ============================================================
   CONSTRUCTION PROJECT MANAGEMENT — MASTER TEMPLATE
   data.js
   ------------------------------------------------------------
   This file intentionally contains NO project-specific data.
   Every value here is either empty or a generic, reusable
   default (default budget categories, default holiday list,
   default navigation). When you clone this repository for a
   new client/project, you do NOT edit this file to "set up"
   a project — all project setup happens from the website itself
   via the onboarding screen (Settings > Create Project), which
   writes directly to Firebase.

   REGISTRY_KEY namespaces this deployment's project list in
   Firebase, so if you ever point two different deployments
   (e.g. this template and an unrelated site) at the SAME
   Firebase project, their project lists never mix. Change this
   per deployment if you want extra separation; otherwise the
   default is fine for a single deployment.
   ============================================================ */

const REGISTRY_KEY = "project_registry";

// Generic, non-project-specific defaults only.
const DEFAULT_SETTINGS = {
  title: "",
  projectNumber: "",
  address: "",
  city: "",
  province: "",
  postalCode: "",
  projectType: "",
  status: "Planning",
  start: "",
  targetCompletion: "",
  projectManager: "",
  superintendent: "",
  projectCoordinator: "",
  description: "",
  notes: "",
  coverImageDataUrl: null,
  companyName: "",
  companyLogoDataUrl: null,
  currency: "USD",
  taxRate: 0,
  taxLabel: "Tax",
  actualExpenseBasis: "Invoice", // "Invoice" | "Paid" | "Manual"
  showFinancialsToClients: false,
};

const DEFAULT_CLIENT = {
  name: "",
  company: "",
  email: "",
  phone: "",
  billingAddress: "",
  mailingAddress: "",
  repName: "",
  repEmail: "",
  repPhone: "",
  notes: "",
};

const DEFAULT_HOLIDAYS = [];

// Generic default budget category *names* only — no amounts, no
// actuals. Admins can rename, delete, or add their own at any time.
const DEFAULT_BUDGET_CATEGORY_NAMES = [
  "Demolition", "Excavation", "Footings", "Foundation", "Framing",
  "Roofing", "Windows", "Doors", "Plumbing", "HVAC", "Electrical",
  "Insulation", "Drywall", "Painting", "Flooring", "Kitchen",
  "Millwork", "Tile", "Exterior", "Landscaping", "Site Rentals",
  "Permits", "Professional Fees", "Other",
];

const PROJECT_TEAM_ROLES = [
  "Project Manager", "Project Coordinator", "Superintendent",
  "Site Supervisor", "Architect", "Engineer", "Designer",
  "Client Representative", "Contractor", "Consultant", "Other",
];

const DOCUMENT_CATEGORIES = [
  "Contracts", "Drawings", "Permits", "Invoices", "Change Orders",
  "Specifications", "Photos", "Reports", "Other",
];

// A brand-new project starts with none of these — this is only the
// list of possible values shown in dropdowns.
const MILESTONE_STATUSES = ["Not Started", "In Progress", "Complete", "Delayed", "On Hold", "Cancelled"];
const CHANGE_ORDER_STATUSES = ["Draft", "Submitted", "Pending Approval", "Approved", "Rejected", "Cancelled"];
const PAYMENT_STATUSES = ["Unpaid", "Partially Paid", "Paid", "Overdue"];
const SITE_RENTAL_TYPES = ["Temporary Fence Rental", "Portable Toilet Rental", "Dumpster", "Equipment Rental", "Temporary Utilities", "Other"];

// Intentionally empty — a brand-new project has zero milestones,
// trades, invoices, payments, change orders, rentals, specs, budget
// entries, documents, or activity. Everything is created from the
// website after onboarding.
const BASELINE_MILESTONES = [];
const BASELINE_TRADES = [];
